In [401]:
# 1) Using the function arange, create an array of 10 integers 'd' from -20 to 25 (inclusive), in steps of 5.

import numpy as np
d= np.linspace(-20,25, num=10)
print(d)

[-20. -15. -10.  -5.   0.   5.  10.  15.  20.  25.]


In [402]:
# 2) Multiply all values in d by 10, storing the result in d2.

d2 = [d*10 for d in d]
print(d2)

[-200.0, -150.0, -100.0, -50.0, 0.0, 50.0, 100.0, 150.0, 200.0, 250.0]


In [403]:
# 3) Add the values stored in d and d2, element-wise, printing the result to the console

print([sum(x) for x in zip(d, d2)])

[-220.0, -165.0, -110.0, -55.0, 0.0, 55.0, 110.0, 165.0, 220.0, 275.0]


In [404]:
# 4) Reshape d2 into a 5x2 array, storing the result in d2.

d2 = np.reshape(d2, (5,2))
print(d2)

[[-200. -150.]
 [-100.  -50.]
 [   0.   50.]
 [ 100.  150.]
 [ 200.  250.]]


In [405]:
# 5) Create an array d3, containing the integers 1,2,3,4,5.

d3 = [1,2,3,4,5]

In [406]:
# 6) Reshape d3 into the necessary shape such that d2*d3 succeeds (hint: broadcasting). Save the result of d2*d3 into d4, and print d4 toto the console.

d3 = np.reshape(d3, (5,1))
d4 = d3 * d2
print(d4)


[[-200. -150.]
 [-200. -100.]
 [   0.  150.]
 [ 400.  600.]
 [1000. 1250.]]


In [407]:
# 7) Print to the console the 1st, 3rd and 5th rows, both columns, of d4. 

d4[::,::2]

array([[-200.],
       [-200.],
       [   0.],
       [ 400.],
       [1000.]])

In [408]:
# 8) Print the object ID of d4 to the console.

print(id(d4))

2540452639536


In [409]:
# 10) Flatten (not reshape) d4 back into a 10x1 array. Print the result to the console. Your output should match: [-200 -150 -200 -100 0 150 400 600 1000 1250]

d4.flatten()


array([-200., -150., -200., -100.,    0.,  150.,  400.,  600., 1000.,
       1250.])